<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'pdffiller\\lib_laravel_env_to_consul\\' => array($baseDir . '/src'),
);
